language: java
before_install:
- openssl aes-256-cbc -K $encrypted_dacfc0476f3d_key -iv $encrypted_dacfc0476f3d_iv
  -in id_rsa_travis.enc -out ~/.ssh/id_rsa_travis -d
- chmod 600 ~/.ssh/id_rsa_travis
- echo -e "Host 35.236.128.26\n\tStrictHostKeyChecking no\n\tIdentityFile
  ~/.ssh/id_rsa_travis" >> ~/.ssh/config
- export MAVEN_OPTS="-Xmn64M -Xmx512M -XX:CompressedClassSpaceSize=96M"
- export JAVA_OPTS="$JAVA_OPTS -XX:CompressedClassSpaceSize=96M"
addons:
  ssh_known_hosts: 35.236.128.26
install: true
script:
  - ./gradlew assemble
after_script:
  - bash .travis/deploy.sh